authentication:
    providers:
    - provider: example
      authenticator: tiled.authenticators:DictionaryAuthenticator
      args:
        users_to_passwords:
          alice: ${ALICE_PASSWORD}
          bob: ${BOB_PASSWORD}
        confirmation_message: "You have logged in as {id}."
    tiled_admins:
      - provider: example
        id: alice

file_extensions:
  edf: application/x-edf
  gb: application/x-gb

access_control:
  access_policy: "tiled.access_control.access_policies:TagBasedAccessPolicy"
  args:
    provider: "example"
    scopes:
    - "read:metadata"
    - "read:data"
    - "write:metadata"
    - "write:data"
    - "delete:revision"
    - "delete:node"
    - "create:node"
    - "register"
    tags_db:
      uri: "/app/data/compiled_tags.db"
    access_tags_parser: "tiled.access_control.access_tags:AccessTagsParser"

trees:
  - path: /
    tree: catalog
    args:
      uri: /app/data/catalog.db
      readable_storage: [/app/data]
      writable_storage: /app/data
      init_if_not_exists: true
      adapters_by_mimetype:
        application/x-edf: splash_tiled.bl733.adapters.edf:EDFAdapter
        application/x-gb: splash_tiled.bl733.adapters.gb:GeneralBinaryPilatus2MAdapter
